#!/usr/bin/env ruby
require_relative 'lib/sudoku_validator'

@validator = SudokuValidator.new(ARGV[0])
validity, status = @validator.validate
puts "This sudoku is #{validity}, and #{status}."
@validator.errors.each { |err| puts err }
