#!/usr/bin/env ruby
require_relative 'lib/sudoku_validator'

@validator = SudokuValidator.new(ARGV[0])
validity, status = @validator.analyze
output = ""
output = "This sudoku is #{validity}"
output += ", and #{status}"
output += "."
puts output
@validator.errors.each { |err| puts err }
